# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='Date reported for transaction.', null=True),
        ),
    ]
