language: python
addons:
    postgresql: "9.4"
    apt:
        packages:
            - "postgresql-9.4-postgis-2.3"
sudo: false
python:
    - "3.6"
    - "3.7"
    - "3.8"
install: 
    - pip install --pre -e .[dev] Django==3.2
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script:
    - ./run-tests.sh
    - flake8
