name: Tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install GIS packages
        run: sudo apt-get install binutils libproj-dev gdal-bin

      - name: Set up PostGIS
        uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql db: test
          postgresql user: test
          postgresql password: test

      - name: Install
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          python -m pip install --no-cache-dir pipenv
          pipenv sync --dev
        shell: bash

      - name: Test
        run: make test
